### ISSUE TITLE
Securly

### ISSUE THREAD

**Issue by Kingaki916** [zek-c/Securly-Kill-V111#2]
They made a new update that just blocks everything if it detects any blocking

**Comment by dragon731012** [comment]
Yeah I saw too but if u clear cookies and restart Chromebook and reenable u get like 5 min to load into site

**Comment by Kingaki916** [comment]
thanks

**Comment by Kingaki916** [comment]
it also gets a lot of false positives half my class today wasn't able to use our chrome books bc of that smh

**Comment by dragon731012** [comment]
Np, tell me if it doesn’t work
