### ISSUE TITLE
bypassi is blocked

### ISSUE THREAD

**Issue by theoxideperson** [zek-c/Securly-Kill-V111#23]
bypassi is blocked by dumb "secure"ly. Is there an alternitave website??

**Comment by zek-c** [comment]
download bypassi.html from the github repository and run it at codepen.io

**Comment by theoxideperson** [comment]
codepen.io is also blocked by securly

**Comment by zek-c** [comment]
skill issue

**Comment by 1010101011101010111** [comment]
Fr

**Comment by ensari1** [comment]
i get a red screen when i drag the button into a new tab

**Comment by zek-c** [comment]
try again until it works and what's your securly version and is it securly or securly classroom
