### ISSUE TITLE
blocked page( differently tho

### ISSUE THREAD

**Issue by josephtee1213** [zek-c/Securly-Kill-V111#33]
every time i drag the link, it opens the kill tab with the switch but it doesn't load. i know this works because I've used it before. but every time i get to the switch it doesn't load it and the URL says blocked but not by securly or go guardian . please fix this if you can, I know your busy with other things though.

**Comment by zek-c** [comment]
this isn't fixable, you have to reload the page a few times and such until it starts working. or you can use skiovox because it just unblocks everything and lets you install any extension you want
https://skiovox.netlify.app
https://github.com/bypassiwastaken/skiovox-helper
