### ISSUE TITLE
Bypassi's insercurly was patched

### ISSUE THREAD

**Issue by MariGames21** [zek-c/Securly-Kill-V111#35]
It says I dont have the right version but it was just working

**Comment by MariGames21** [comment]
any fixes?

**Comment by zek-c** [comment]
it's not patched just doesn't work for you

**Comment by MariGames21** [comment]
But it was just working then it stopped. Anyway I can get running once more?

**Comment by MariGames21** [comment]
I have even tried powerwashing then using it

**Comment by zek-c** [comment]
i don't know without more information, it could be anything

**Comment by replitidk** [comment]
the schools just updated securly and stuff so it wont work morale of the story move on

**Comment by replitidk** [comment]
@MariGames21
