### ISSUE TITLE
How do you fix when it says "You don't have an adequate version of Securly installed."

### ISSUE THREAD

**Issue by 26noldej** [zek-c/Securly-Kill-V111#46]
When I open up the insecurly, this is what it says, how should I fix it?
![Screenshot 2024-01-04 9 14 57 AM](https://github.com/zek-c/Securly-Kill-V111/assets/155651946/64685c07-0e4c-4379-90da-72768b0df7f1)

**Comment by zek-c** [comment]
securly is slowly working towards patching this, but this can also mean your securly isn't the right version/ installed from unknown source. you can use skiovox if you're on V118 or lower, as it's patched on the latest 119
