### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by Boom4Life** [zek-c/Securly-Kill-V111#5]
it got patched, u cant go to securly.com and use it now.

**Comment by Boom4Life** [comment]
im pretty sure that they disabled bookmarks with js code in em, tested other websites and they dont work with that or using alert()

**Comment by zek-c** [comment]
this is your school specifically it works for me still, i will try to find a workaround

**Comment by Boom4Life** [comment]
ik

**Comment by Boom4Life** [comment]
is their another way of injecting it or is that the only way.

**Comment by Boom4Life** [comment]
most schools have bookmarklets disabled

**Comment by zek-c** [comment]
lol im finding another way
