### ISSUE TITLE
chrome://network/#state is blocked for me 

### ISSUE THREAD

**Issue by dragonballsucks** [zek-c/Securly-Kill-V111#60]
![Screenshot 2024-02-09 2 21 21 PM](https://github.com/zek-c/Securly-Kill-V111/assets/159577589/4c69ab29-40b4-4b76-be59-8b43e5ade9bd)

is there any other way that i can access chrome://network/#state

**Comment by zek-c** [comment]
no, you're cooked 😭🙏

**Comment by dragonballsucks** [comment]
tuff
