### ISSUE TITLE
YouTube videos now restricted

### ISSUE THREAD

**Issue by unbreakify** [zek-c/Securly-Kill-V111#65]
YouTube videos are now restricted despite using CauDNS. Im using my personal account so this does feel like a breach of privacy considering its my personal account and shouldn't be blocked by some shitty restriction.

**"_Video unavailable
This video is restricted. Please check the Google Workspace administrator and/or the network administrator restrictions."_**

**Comment by zek-c** [comment]
why is this my problem 😭🙏 your school blocked youtube it's not my fault
