### ISSUE TITLE
network sign in

### ISSUE THREAD

**Issue by typicallol** [zek-c/Securly-Kill-V111#67]
so uh, when i use caudns, it says i have to sign in to the network, but i think it might be something to do with the dns server. But then sometimes when i try to use caudns again the onc file wont even change the name servers. pls fix

**Comment by dragon731012** [comment]
The network problem isn’t my fault, omadadns is hosting server. Make sure you are using the correct revive file, or redownload the zip.

**Comment by typicallol** [comment]
i did that, but it dont work can u like check omadadns to see whats happening or get another server

**Comment by typicallol** [comment]
nvm it works now thx
