### ISSUE TITLE
What if chrome://network is Blocked?

### ISSUE THREAD

**Issue by Bruhsbegood128943** [zek-c/Securly-Kill-V111#70]
So I tried to do CauDNS but chrome://network is blocked. Could you help with this issue?

**Comment by zek-c** [comment]
impossible, can't bypass that

**Comment by dragon731012** [comment]
If you can manually edit name servers, set first one to 167.86.91.171

**Comment by A60-Wagyu** [comment]
> If you can manually edit name servers, set first one to 167.86.91.171

then what do you do?
