### ISSUE TITLE
chrome://network is unreachable 

### ISSUE THREAD

**Issue by dragonballsucks** [zek-c/Securly-Kill-V111#72]

**Comment by dragonballsucks** [comment]
But I was using a phone instead of school chromebook

**Comment by typicallol** [comment]
bruv what who would use a phone to use a chromebook unblocking method

**Comment by dragonballsucks** [comment]
😔

**Comment by zek-c** [comment]
are you special 😭🙏 why do you think a chrome page would work on a phone
