### ISSUE TITLE
Serculy kill not working?

### ISSUE THREAD

**Issue by esdist60** [zek-c/Securly-Kill-V111#76]
when I try to use the serculy kill it shows up as "Global
Category: <style>*{visibility:hidden}</style> <iframe srcdoc="<script src='/e3b3c34b-fd68-43a1-9013-fcdc8100d6ba'></script>">" and does not work.

**Comment by zek-c** [comment]
insecurly does not work anymore, downgrade and use bookmarklet, or cauDNS

**Comment by esdist60** [comment]
cauDns worked
