### ISSUE TITLE
Blocked websites

### ISSUE THREAD

**Issue by NeverEndingRadicalDude** [zek-c/Securly-Kill-V111#78]
There are several websites that are blocked on the dns, websites like https://fognetwork.github.io/Ingot/ which I am trying to use to also disable the hapara extension. When I try to connect to the website on the dns it says website category is blocked, I know its not the wifi I'm on because websites like reddit which are blocked by the wifi instead just timeout after not connecting for like 5 minutes.

**Comment by zek-c** [comment]
it is for sure the wifi blocks.
