### ISSUE TITLE
incognito mode

### ISSUE THREAD

**Issue by Boom4Life** [zek-c/Securly-Kill-V111#9]
there was a way that was blocked to have incognito mode, tell me if it works at ur school.
1. go to the guest wifi or wifi with a popup ( make sure its in a new window not in chrome, schools patched it by making it open on chrome) 
2. right click the button that will allow you to use the wifi.
3. click open in a new tab
4. it should open a window without extensions and says it is a incog window on the top right.
tell me if it work

**Comment by zek-c** [comment]
can you be more clear bro what does this even mean
